version: '3.8'
services:
  lmcustomerms:
    build: .
    container_name: lmcustomerms
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_APPLICATION_NAME=LMCustomerMS
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8090/eureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/cliente_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD= #corroborar si es espacio en blanco o "".
    networks:
      - libmark-network

networks:
  libmark-network:
    external: true
